name: build

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
concurrency:
  group: pipeline-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    timeout-minutes: 10
    env:
      WOTR_PATH: ../../libs
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet build ./src --no-restore -c release
    - name: Test
      run: dotnet test ./src --no-build --verbosity normal
